openapi: 3.0.0
info:
  title: OSU Recap Transparent Proxy
  description: |
    Прозрачный API Gateway для мини-приложения "Итоги семестра в ОГУ".
    
    Gateway выполняет ТОЛЬКО:
    - проксирование запросов /api/osu/* на https://www.osu.ru/*
    
    Gateway:
    - не хранит данные
    - не логирует тела запросов
    - не изменяет payload
  version: 1.0.0

servers:
- url: https://d5dqok8k42ev7cutajq7.z7jmlavt.apigw.yandexcloud.net
openapi: 3.0.0
paths:
  /docs:
    get:
      summary: Swagger документация
      x-yc-apigateway-integration:
        type: swagger

  /api/osu/{proxy+}:
    x-yc-apigateway-any-method:
      summary: Transparent proxy to osu.ru
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string

      x-yc-apigateway-integration:
        type: http
        method: POST
        url: https://www.osu.ru/{proxy}

        path:
          proxy: proxy

        query:
          '*': '*'

        headers:
          Host: www.osu.ru
          '*': '*'

        body:
          '*': '*'

        timeout: 30
